version: '3.9'

services:

  influxdb:
    image: influxdb:2.7

    container_name: cubesat-influxdb

    restart: always

    ports:
      - "8086:8086"

    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  influxdb_data: